name: r-pixelator
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - r-arrow
  - r-cli
  - r-duckdb
  - r-ggplot2
  - r-ggraph
  - r-glue
  - r-graphlayouts
  - r-igraph
  - r-jsonlite
  - r-rlang
  - r-scales
  - r-stringr
  - r-testthat
  - r-tibble
  - r-tidygraph
  - r-tidyr
  - r-dplyr
  - r-seuratobject
  - r-seurat
  - r-matrix
  - r-patchwork
  - r-pheatmap
  - r-duckdb
  - r-hdf5r
  - r-pbapply
  - r-fs
  - r-zip
  - r-plotly
  - r-duckdb
