name: r-pixelator
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - r-base
  - r-remotes
  - r-arrow
  - r-cli
  - r-duckdb
  - r-ggplot2
  - r-ggraph
  - r-glue
  - r-graphlayouts
  - r-igraph
  - r-jsonlite
  - r-rlang
  - r-scales
  - r-stringr
  - r-testthat
  - r-tibble
  - r-tidygraph
  - r-tidyr
  - r-dplyr
  - r-seurat >= 5.0.0
  - r-seuratobject >= 5.0.0
  - r-mclust
  - bioconductor-limma
  - r-harmony
  - r-matrix
  - r-patchwork
  - r-pheatmap
  - r-duckdb
  - r-hdf5r
  - r-pbapply
  - r-dbplyr
  - r-fs
  - r-zip
  - r-plotly
  - r-duckdb
  - r-lifecycle
  - r-devtools
  - r-styler
  - r-lintr
  - r-spelling
  - r-graphlayouts
  - r-mclust
  - r-pheatmap
  - r-scales
  - r-duckdb
  - r-mass
